'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MARKET_INFO
    Public Property ID As Integer
    Public Property MARKET_SIZE As Nullable(Of Decimal)
    Public Property GROWTH_RATE As Nullable(Of Decimal)
    Public Property VARIATION_TYPE As String
    Public Property VARIATION_SD As Nullable(Of Decimal)
    Public Property INITIAL_QUALITY As Nullable(Of Decimal)
    Public Property VARIATION_PARAM_1 As Nullable(Of Decimal)
    Public Property VARIATION_PARAM_2 As Nullable(Of Decimal)
    Public Property VARIATION_PARAM_3 As Nullable(Of Decimal)
    Public Property IS_DELETED As Nullable(Of Boolean)

    Public Overridable Property GAME_FIRM As ICollection(Of GAME_FIRM) = New HashSet(Of GAME_FIRM)

End Class
