'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ACTION_TRANSACTIONS
    Public Property ID As Integer
    Public Property DEVICE_LINK_ID As Nullable(Of Integer)
    Public Property PERSONNEL_LINK_ID As Nullable(Of Integer)
    Public Property ACTION_PERFORMED As Nullable(Of Integer)
    Public Property DESCRIPTION As String
    Public Property DATE_TIME As Nullable(Of Date)
    Public Property IS_DELETED As Nullable(Of Boolean)

    Public Overridable Property APP_DEVICES As APP_DEVICES
    Public Overridable Property USER As USER

End Class
