'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class APP_DEVICES
    Public Property ID As Integer
    Public Property PERSONNEL_LINK_ID As Nullable(Of Integer)
    Public Property DEVICE_TYPE As Nullable(Of Integer)
    Public Property DEVICE_UNIQUE_ID As String
    Public Property AUTHENTICATION_TOKEN As String
    Public Property PUSH_NOTIFICATION_TOKEN As String
    Public Property CURRENT_ARC_APP_VERSION As String
    Public Property CURRENT_API_VERSION As String
    Public Property LOCATION As String
    Public Property LAST_ACCESSED_DATE_TIME As Nullable(Of Date)
    Public Property DATE_TIME_DEVICE_ADDED As Nullable(Of Date)
    Public Property IS_DELETED As Nullable(Of Boolean)

    Public Overridable Property ACTION_TRANSACTIONS As ICollection(Of ACTION_TRANSACTIONS) = New HashSet(Of ACTION_TRANSACTIONS)
    Public Overridable Property USER As USER

End Class
