'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FILE_STORAGE
    Public Property ID As Integer
    Public Property FILE_NAME As String
    Public Property DIRECTORY As String
    Public Property DATABASE_TABLE As Nullable(Of Short)
    Public Property DATABASE_TABLE_ID As Nullable(Of Integer)
    Public Property SALES_SCHEDULING_ID As Nullable(Of Integer)
    Public Property IS_DELETED As Nullable(Of Boolean)
    Public Property FILE_STRING As String

    Public Overridable Property CONTENT_MANAGER As ICollection(Of CONTENT_MANAGER) = New HashSet(Of CONTENT_MANAGER)

End Class
