'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GAME
    Public Property ID As Integer
    Public Property GAME_NAME As String
    Public Property GAME_TYPE_LINK_ID As Nullable(Of Integer)
    Public Property PERIOD_LINK_ID As Nullable(Of Integer)
    Public Property IS_DELETED As Nullable(Of Boolean)

    Public Overridable Property GAME_FIRM As ICollection(Of GAME_FIRM) = New HashSet(Of GAME_FIRM)
    Public Overridable Property GAME_TYPE As GAME_TYPE
    Public Overridable Property PERIOD As PERIOD
    Public Overridable Property USER_USER_ROLE_GAME_RELATIONSHIP As ICollection(Of USER_USER_ROLE_GAME_RELATIONSHIP) = New HashSet(Of USER_USER_ROLE_GAME_RELATIONSHIP)

End Class
