'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GAME_FIRM
    Public Property ID As Integer
    Public Property FIRM_NAME As String
    Public Property GAME_LINK_ID As Nullable(Of Integer)
    Public Property IS_DELETED As Nullable(Of Boolean)

    Public Overridable Property GAME As GAME
    Public Overridable Property FIRM_USER_RELATIONSHIP As ICollection(Of FIRM_USER_RELATIONSHIP) = New HashSet(Of FIRM_USER_RELATIONSHIP)

End Class
