'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PERIOD
    Public Property ID As Integer
    Public Property PERIOD_NAME As String
    Public Property PERIOD_NUMBER As Nullable(Of Integer)
    Public Property STATUS As Nullable(Of Integer)
    Public Property START_TIME As Nullable(Of Date)
    Public Property END_TIME As Nullable(Of Date)
    Public Property IS_DELETED As Nullable(Of Boolean)

    Public Overridable Property GAMEs As ICollection(Of GAME) = New HashSet(Of GAME)

End Class
