'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BALANCE_SHEET
    Public Property ID As Integer
    Public Property TOTAL_ASSET As Nullable(Of Decimal)
    Public Property TOTAL_LIABILITY As Nullable(Of Decimal)
    Public Property TOTAL_EQUITY As Nullable(Of Decimal)
    Public Property INITIAL_ASSET As Nullable(Of Decimal)
    Public Property INITIAL_LIABILITY As Nullable(Of Decimal)
    Public Property INITIAL_EQUITY As Nullable(Of Decimal)
    Public Property IS_DELETED As Nullable(Of Boolean)
    Public Property LAST_MODIFIED As Nullable(Of Date)

    Public Overridable Property BALANCE_SHEET_TRANSACTION As ICollection(Of BALANCE_SHEET_TRANSACTION) = New HashSet(Of BALANCE_SHEET_TRANSACTION)
    Public Overridable Property GAME_FIRM As ICollection(Of GAME_FIRM) = New HashSet(Of GAME_FIRM)

End Class
