'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BALANCE_SHEET_TRANSACTION
    Public Property ID As Integer
    Public Property TRANSACTION_STATUS As Nullable(Of Integer)
    Public Property BALANCE_SHEET_LINK_ID As Nullable(Of Integer)
    Public Property TRANSACTION_AMOUNT As Nullable(Of Decimal)
    Public Property TRANSACTION_NAME As String
    Public Property TRANSACTION_TYPE As Nullable(Of Integer)
    Public Property TRANSACTION_JSON As String
    Public Property IS_DELETED As Nullable(Of Boolean)
    Public Property DATE_TIME_INSERTED As Nullable(Of Date)
    Public Property REVENUE_AND_COST_LINK_ID As Nullable(Of Integer)

    Public Overridable Property BALANCE_SHEET As BALANCE_SHEET
    Public Overridable Property REVENUE_AND_COST As REVENUE_AND_COST

End Class
