'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CONTENT_MANAGER
    Public Property ID As Integer
    Public Property CONTENT_NAME As String
    Public Property CONTENT_TYPE As String
    Public Property CONTENT_GROUP As String
    Public Property CONTENT_CATEGORY As String
    Public Property CONTENT_THUMBNAIL As String
    Public Property IMAGE_STRING_ID_LINK As Nullable(Of Integer)
    Public Property IS_DELETED As Nullable(Of Boolean)
    Public Property PERSONNEL_LINK_ID As Nullable(Of Integer)
    Public Property CREATED_DATE_TIME As Nullable(Of Date)
    Public Property EDIT_DATE_TIME As Nullable(Of Date)
    Public Property NOTES As String
    Public Property CONTENT_MANAGER_TYPE As Nullable(Of Integer)
    Public Property FILE_STORAGE_LINK_ID As Nullable(Of Integer)
    Public Property AUDIO_STORAGE_LINK_ID As Nullable(Of Integer)
    Public Property VIDEO_STORAGE_LINK_ID As Nullable(Of Integer)
    Public Property PARENT_VERSION_LINK_ID As Nullable(Of Integer)
    Public Property VERSION_NUMBER As String
    Public Property IS_ARCHIVED As Nullable(Of Boolean)
    Public Property IS_DEFAULT As Nullable(Of Boolean)

    Public Overridable Property AUDIO_STORAGE As AUDIO_STORAGE
    Public Overridable Property CONTENT_MANAGER1 As ICollection(Of CONTENT_MANAGER) = New HashSet(Of CONTENT_MANAGER)
    Public Overridable Property CONTENT_MANAGER2 As CONTENT_MANAGER
    Public Overridable Property FILE_STORAGE As FILE_STORAGE
    Public Overridable Property VIDEO_STORAGE As VIDEO_STORAGE
    Public Overridable Property GAMEs As ICollection(Of GAME) = New HashSet(Of GAME)
    Public Overridable Property GAME_TYPE As ICollection(Of GAME_TYPE) = New HashSet(Of GAME_TYPE)
    Public Overridable Property IMAGE_STRING As IMAGE_STRING
    Public Overridable Property USER As USER
    Public Overridable Property USERs As ICollection(Of USER) = New HashSet(Of USER)

End Class
