
-- --------------------------------------------------
-- Entity Designer DDL Script for SQL Server 2005, 2008, 2012 and Azure
-- --------------------------------------------------
-- Date Created: 02/22/2018 10:14:02
-- Generated from EDMX file: C:\Users\pc\Documents\Visual Studio 2017\Projects\FYPComponents\GameAdministratorCenter\GameAdministratorCenter.Contracts\FYP_DATABASE.edmx
-- --------------------------------------------------

SET QUOTED_IDENTIFIER OFF;
GO
USE [FYP_DATABASE];
GO
IF SCHEMA_ID(N'dbo') IS NULL EXECUTE(N'CREATE SCHEMA [dbo]');
GO

-- --------------------------------------------------
-- Dropping existing FOREIGN KEY constraints
-- --------------------------------------------------

IF OBJECT_ID(N'[dbo].[FK_ARC_APP_ACTION_TRANSACTIONS_ARC_APP_DEVICES]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[ACTION_TRANSACTIONS] DROP CONSTRAINT [FK_ARC_APP_ACTION_TRANSACTIONS_ARC_APP_DEVICES];
GO
IF OBJECT_ID(N'[dbo].[FK_ARC_APP_ACTION_TRANSACTIONS_PERSONNEL]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[ACTION_TRANSACTIONS] DROP CONSTRAINT [FK_ARC_APP_ACTION_TRANSACTIONS_PERSONNEL];
GO
IF OBJECT_ID(N'[dbo].[FK_ARC_APP_DEVICES_PERSONNEL]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[APP_DEVICES] DROP CONSTRAINT [FK_ARC_APP_DEVICES_PERSONNEL];
GO
IF OBJECT_ID(N'[dbo].[FK_BALANCE_SHEET_TRANSACTION_BALANCE_SHEET]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[BALANCE_SHEET_TRANSACTION] DROP CONSTRAINT [FK_BALANCE_SHEET_TRANSACTION_BALANCE_SHEET];
GO
IF OBJECT_ID(N'[dbo].[FK_BALANCE_SHEET_TRANSACTION_REVENUE_AND_COST]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[BALANCE_SHEET_TRANSACTION] DROP CONSTRAINT [FK_BALANCE_SHEET_TRANSACTION_REVENUE_AND_COST];
GO
IF OBJECT_ID(N'[dbo].[FK_CONTENT_MANAGER_AUDIO_STORAGE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CONTENT_MANAGER] DROP CONSTRAINT [FK_CONTENT_MANAGER_AUDIO_STORAGE];
GO
IF OBJECT_ID(N'[dbo].[FK_CONTENT_MANAGER_CONTENT_MANAGER]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CONTENT_MANAGER] DROP CONSTRAINT [FK_CONTENT_MANAGER_CONTENT_MANAGER];
GO
IF OBJECT_ID(N'[dbo].[FK_CONTENT_MANAGER_FILE_STORAGE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CONTENT_MANAGER] DROP CONSTRAINT [FK_CONTENT_MANAGER_FILE_STORAGE];
GO
IF OBJECT_ID(N'[dbo].[FK_CONTENT_MANAGER_VIDEO_STORAGE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CONTENT_MANAGER] DROP CONSTRAINT [FK_CONTENT_MANAGER_VIDEO_STORAGE];
GO
IF OBJECT_ID(N'[dbo].[FK_FINANCE_DECISIONS_FIRM_FINANCE_DECISIONS]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[FINANCE_DECISIONS] DROP CONSTRAINT [FK_FINANCE_DECISIONS_FIRM_FINANCE_DECISIONS];
GO
IF OBJECT_ID(N'[dbo].[FK_FINANCE_DECISIONS_PERIOD_FINANCE_DECISIONS]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[FINANCE_DECISIONS] DROP CONSTRAINT [FK_FINANCE_DECISIONS_PERIOD_FINANCE_DECISIONS];
GO
IF OBJECT_ID(N'[dbo].[FK_FINANCE_DECISIONS_USER_FINANCE_DECISIONS]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[FINANCE_DECISIONS] DROP CONSTRAINT [FK_FINANCE_DECISIONS_USER_FINANCE_DECISIONS];
GO
IF OBJECT_ID(N'[dbo].[FK_GAME_CONTENT_MANAGER]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[GAME] DROP CONSTRAINT [FK_GAME_CONTENT_MANAGER];
GO
IF OBJECT_ID(N'[dbo].[FK_GAME_FIRM_BALANCE_SHEET]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[GAME_FIRM] DROP CONSTRAINT [FK_GAME_FIRM_BALANCE_SHEET];
GO
IF OBJECT_ID(N'[dbo].[FK_GAME_FIRM_GAME]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[GAME_FIRM] DROP CONSTRAINT [FK_GAME_FIRM_GAME];
GO
IF OBJECT_ID(N'[dbo].[FK_GAME_FIRM_MARKET_INFO_GAME_FIRM]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[GAME_FIRM] DROP CONSTRAINT [FK_GAME_FIRM_MARKET_INFO_GAME_FIRM];
GO
IF OBJECT_ID(N'[dbo].[FK_GAME_GAME_TYPE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[GAME] DROP CONSTRAINT [FK_GAME_GAME_TYPE];
GO
IF OBJECT_ID(N'[dbo].[FK_GAME_TYPE_CONTENT_MANAGER]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[GAME_TYPE] DROP CONSTRAINT [FK_GAME_TYPE_CONTENT_MANAGER];
GO
IF OBJECT_ID(N'[dbo].[FK_IMAGE_STRING_MANAGER_IMAGE_STRING]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CONTENT_MANAGER] DROP CONSTRAINT [FK_IMAGE_STRING_MANAGER_IMAGE_STRING];
GO
IF OBJECT_ID(N'[dbo].[FK_IMAGE_STRING_MANAGER_PERSONNEL]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CONTENT_MANAGER] DROP CONSTRAINT [FK_IMAGE_STRING_MANAGER_PERSONNEL];
GO
IF OBJECT_ID(N'[dbo].[FK_INCOME_STATEMENT_FIRM_INCOME_STATEMENT]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[INCOME_STATEMENT] DROP CONSTRAINT [FK_INCOME_STATEMENT_FIRM_INCOME_STATEMENT];
GO
IF OBJECT_ID(N'[dbo].[FK_INCOME_STATEMENT_PERIOD_INCOME_STATEMENT]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[INCOME_STATEMENT] DROP CONSTRAINT [FK_INCOME_STATEMENT_PERIOD_INCOME_STATEMENT];
GO
IF OBJECT_ID(N'[dbo].[FK_MARKETING_DECISIONS_GAME_FIRM]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[MARKETING_DECISIONS] DROP CONSTRAINT [FK_MARKETING_DECISIONS_GAME_FIRM];
GO
IF OBJECT_ID(N'[dbo].[FK_MARKETING_DECISIONS_PERIOD]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[MARKETING_DECISIONS] DROP CONSTRAINT [FK_MARKETING_DECISIONS_PERIOD];
GO
IF OBJECT_ID(N'[dbo].[FK_MARKETING_DECISIONS_USER]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[MARKETING_DECISIONS] DROP CONSTRAINT [FK_MARKETING_DECISIONS_USER];
GO
IF OBJECT_ID(N'[dbo].[FK_PERIOD_GAME]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PERIOD] DROP CONSTRAINT [FK_PERIOD_GAME];
GO
IF OBJECT_ID(N'[dbo].[FK_PRODUCTION_DECISIONS_GAME_FIRM]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PRODUCTION_DECISIONS] DROP CONSTRAINT [FK_PRODUCTION_DECISIONS_GAME_FIRM];
GO
IF OBJECT_ID(N'[dbo].[FK_PRODUCTION_DECISIONS_PERIOD]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PRODUCTION_DECISIONS] DROP CONSTRAINT [FK_PRODUCTION_DECISIONS_PERIOD];
GO
IF OBJECT_ID(N'[dbo].[FK_PRODUCTION_DECISIONS_REVENUE_AND_COST]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PRODUCTION_DECISIONS] DROP CONSTRAINT [FK_PRODUCTION_DECISIONS_REVENUE_AND_COST];
GO
IF OBJECT_ID(N'[dbo].[FK_PRODUCTION_DECISIONS_USER]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PRODUCTION_DECISIONS] DROP CONSTRAINT [FK_PRODUCTION_DECISIONS_USER];
GO
IF OBJECT_ID(N'[dbo].[FK_RESULT_FINANCE_DECISIONS]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[RESULT] DROP CONSTRAINT [FK_RESULT_FINANCE_DECISIONS];
GO
IF OBJECT_ID(N'[dbo].[FK_RESULT_GAME_FIRM]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[RESULT] DROP CONSTRAINT [FK_RESULT_GAME_FIRM];
GO
IF OBJECT_ID(N'[dbo].[FK_RESULT_GAME_FIRM1]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[RESULT] DROP CONSTRAINT [FK_RESULT_GAME_FIRM1];
GO
IF OBJECT_ID(N'[dbo].[FK_RESULT_MARKETING_DECISIONS]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[RESULT] DROP CONSTRAINT [FK_RESULT_MARKETING_DECISIONS];
GO
IF OBJECT_ID(N'[dbo].[FK_RESULT_PERIOD]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[RESULT] DROP CONSTRAINT [FK_RESULT_PERIOD];
GO
IF OBJECT_ID(N'[dbo].[FK_RESULT_PRODUCTION_DECISIONS]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[RESULT] DROP CONSTRAINT [FK_RESULT_PRODUCTION_DECISIONS];
GO
IF OBJECT_ID(N'[dbo].[FK_RESULT_RND_DECISIONS]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[RESULT] DROP CONSTRAINT [FK_RESULT_RND_DECISIONS];
GO
IF OBJECT_ID(N'[dbo].[FK_REVENUE_AND_COST_GAME_FIRM]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[REVENUE_AND_COST] DROP CONSTRAINT [FK_REVENUE_AND_COST_GAME_FIRM];
GO
IF OBJECT_ID(N'[dbo].[FK_REVENUE_AND_COST_PERIOD]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[REVENUE_AND_COST] DROP CONSTRAINT [FK_REVENUE_AND_COST_PERIOD];
GO
IF OBJECT_ID(N'[dbo].[FK_REVENUE_AND_COST_REVENUE_AND_COST]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[REVENUE_AND_COST] DROP CONSTRAINT [FK_REVENUE_AND_COST_REVENUE_AND_COST];
GO
IF OBJECT_ID(N'[dbo].[FK_RND_DECISIONS_GAME_FIRM]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[RND_DECISIONS] DROP CONSTRAINT [FK_RND_DECISIONS_GAME_FIRM];
GO
IF OBJECT_ID(N'[dbo].[FK_RND_DECISIONS_PERIOD]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[RND_DECISIONS] DROP CONSTRAINT [FK_RND_DECISIONS_PERIOD];
GO
IF OBJECT_ID(N'[dbo].[FK_RND_DECISIONS_REVENUE_AND_COST]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[RND_DECISIONS] DROP CONSTRAINT [FK_RND_DECISIONS_REVENUE_AND_COST];
GO
IF OBJECT_ID(N'[dbo].[FK_RND_DECISIONS_USER]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[RND_DECISIONS] DROP CONSTRAINT [FK_RND_DECISIONS_USER];
GO
IF OBJECT_ID(N'[dbo].[FK_USER_CONTENT_MANAGER]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[USER] DROP CONSTRAINT [FK_USER_CONTENT_MANAGER];
GO
IF OBJECT_ID(N'[dbo].[FK_USER_USER_ROLE_GAME_RELATIONSHIP_GAME]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[USER_USER_ROLE_GAME_FIRM_RELATIONSHIP] DROP CONSTRAINT [FK_USER_USER_ROLE_GAME_RELATIONSHIP_GAME];
GO
IF OBJECT_ID(N'[dbo].[FK_USER_USER_ROLE_GAME_RELATIONSHIP_GAME_FIRM]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[USER_USER_ROLE_GAME_FIRM_RELATIONSHIP] DROP CONSTRAINT [FK_USER_USER_ROLE_GAME_RELATIONSHIP_GAME_FIRM];
GO
IF OBJECT_ID(N'[dbo].[FK_USER_USER_ROLE_GAME_RELATIONSHIP_USER]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[USER_USER_ROLE_GAME_FIRM_RELATIONSHIP] DROP CONSTRAINT [FK_USER_USER_ROLE_GAME_RELATIONSHIP_USER];
GO
IF OBJECT_ID(N'[dbo].[FK_USER_USER_ROLE_GAME_RELATIONSHIP_USER_ROLE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[USER_USER_ROLE_GAME_FIRM_RELATIONSHIP] DROP CONSTRAINT [FK_USER_USER_ROLE_GAME_RELATIONSHIP_USER_ROLE];
GO
IF OBJECT_ID(N'[dbo].[FK_WEB_API_AUTHORIZATION_PERSONNEL]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[WEB_API_AUTHORIZATION] DROP CONSTRAINT [FK_WEB_API_AUTHORIZATION_PERSONNEL];
GO
IF OBJECT_ID(N'[dbo].[FK_WEB_API_TRANSACTION_WEB_API_AUTHORIZATION]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[WEB_API_TRANSACTION] DROP CONSTRAINT [FK_WEB_API_TRANSACTION_WEB_API_AUTHORIZATION];
GO

-- --------------------------------------------------
-- Dropping existing tables
-- --------------------------------------------------

IF OBJECT_ID(N'[dbo].[ACTION_TRANSACTIONS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[ACTION_TRANSACTIONS];
GO
IF OBJECT_ID(N'[dbo].[APP_DEVICES]', 'U') IS NOT NULL
    DROP TABLE [dbo].[APP_DEVICES];
GO
IF OBJECT_ID(N'[dbo].[AUDIO_STORAGE]', 'U') IS NOT NULL
    DROP TABLE [dbo].[AUDIO_STORAGE];
GO
IF OBJECT_ID(N'[dbo].[BALANCE_SHEET]', 'U') IS NOT NULL
    DROP TABLE [dbo].[BALANCE_SHEET];
GO
IF OBJECT_ID(N'[dbo].[BALANCE_SHEET_TRANSACTION]', 'U') IS NOT NULL
    DROP TABLE [dbo].[BALANCE_SHEET_TRANSACTION];
GO
IF OBJECT_ID(N'[dbo].[CONTENT_MANAGER]', 'U') IS NOT NULL
    DROP TABLE [dbo].[CONTENT_MANAGER];
GO
IF OBJECT_ID(N'[dbo].[FILE_STORAGE]', 'U') IS NOT NULL
    DROP TABLE [dbo].[FILE_STORAGE];
GO
IF OBJECT_ID(N'[dbo].[FINANCE_DECISIONS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[FINANCE_DECISIONS];
GO
IF OBJECT_ID(N'[dbo].[GAME]', 'U') IS NOT NULL
    DROP TABLE [dbo].[GAME];
GO
IF OBJECT_ID(N'[dbo].[GAME_FIRM]', 'U') IS NOT NULL
    DROP TABLE [dbo].[GAME_FIRM];
GO
IF OBJECT_ID(N'[dbo].[GAME_TYPE]', 'U') IS NOT NULL
    DROP TABLE [dbo].[GAME_TYPE];
GO
IF OBJECT_ID(N'[dbo].[IMAGE_STRING]', 'U') IS NOT NULL
    DROP TABLE [dbo].[IMAGE_STRING];
GO
IF OBJECT_ID(N'[dbo].[INCOME_STATEMENT]', 'U') IS NOT NULL
    DROP TABLE [dbo].[INCOME_STATEMENT];
GO
IF OBJECT_ID(N'[dbo].[MARKET_INFO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[MARKET_INFO];
GO
IF OBJECT_ID(N'[dbo].[MARKETING_DECISIONS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[MARKETING_DECISIONS];
GO
IF OBJECT_ID(N'[dbo].[PERIOD]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PERIOD];
GO
IF OBJECT_ID(N'[dbo].[PRODUCTION_DECISIONS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PRODUCTION_DECISIONS];
GO
IF OBJECT_ID(N'[dbo].[RESULT]', 'U') IS NOT NULL
    DROP TABLE [dbo].[RESULT];
GO
IF OBJECT_ID(N'[dbo].[REVENUE_AND_COST]', 'U') IS NOT NULL
    DROP TABLE [dbo].[REVENUE_AND_COST];
GO
IF OBJECT_ID(N'[dbo].[RND_DECISIONS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[RND_DECISIONS];
GO
IF OBJECT_ID(N'[dbo].[USER]', 'U') IS NOT NULL
    DROP TABLE [dbo].[USER];
GO
IF OBJECT_ID(N'[dbo].[USER_ROLE]', 'U') IS NOT NULL
    DROP TABLE [dbo].[USER_ROLE];
GO
IF OBJECT_ID(N'[dbo].[USER_USER_ROLE_GAME_FIRM_RELATIONSHIP]', 'U') IS NOT NULL
    DROP TABLE [dbo].[USER_USER_ROLE_GAME_FIRM_RELATIONSHIP];
GO
IF OBJECT_ID(N'[dbo].[VIDEO_STORAGE]', 'U') IS NOT NULL
    DROP TABLE [dbo].[VIDEO_STORAGE];
GO
IF OBJECT_ID(N'[dbo].[WEB_API_AUTHORIZATION]', 'U') IS NOT NULL
    DROP TABLE [dbo].[WEB_API_AUTHORIZATION];
GO
IF OBJECT_ID(N'[dbo].[WEB_API_TRANSACTION]', 'U') IS NOT NULL
    DROP TABLE [dbo].[WEB_API_TRANSACTION];
GO

-- --------------------------------------------------
-- Creating all tables
-- --------------------------------------------------

-- Creating table 'ACTION_TRANSACTIONS'
CREATE TABLE [dbo].[ACTION_TRANSACTIONS] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [DEVICE_LINK_ID] int  NULL,
    [PERSONNEL_LINK_ID] int  NULL,
    [ACTION_PERFORMED] int  NULL,
    [DESCRIPTION] nvarchar(max)  NULL,
    [DATE_TIME] datetime  NULL,
    [IS_DELETED] bit  NULL
);
GO

-- Creating table 'APP_DEVICES'
CREATE TABLE [dbo].[APP_DEVICES] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [PERSONNEL_LINK_ID] int  NULL,
    [DEVICE_TYPE] int  NULL,
    [DEVICE_UNIQUE_ID] nvarchar(max)  NULL,
    [AUTHENTICATION_TOKEN] nvarchar(max)  NULL,
    [PUSH_NOTIFICATION_TOKEN] nvarchar(max)  NULL,
    [CURRENT_ARC_APP_VERSION] nvarchar(800)  NULL,
    [CURRENT_API_VERSION] nvarchar(800)  NULL,
    [LOCATION] nvarchar(max)  NULL,
    [LAST_ACCESSED_DATE_TIME] datetime  NULL,
    [DATE_TIME_DEVICE_ADDED] datetime  NULL,
    [IS_DELETED] bit  NULL
);
GO

-- Creating table 'AUDIO_STORAGE'
CREATE TABLE [dbo].[AUDIO_STORAGE] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [NAME] nvarchar(500)  NULL,
    [AUDIO_STRING] nvarchar(max)  NULL,
    [IS_DELETED] bit  NULL
);
GO

-- Creating table 'BALANCE_SHEET'
CREATE TABLE [dbo].[BALANCE_SHEET] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [TOTAL_ASSET] decimal(18,5)  NULL,
    [TOTAL_LIABILITY] decimal(18,5)  NULL,
    [TOTAL_EQUITY] decimal(18,5)  NULL,
    [INITIAL_ASSET] decimal(18,5)  NULL,
    [INITIAL_LIABILITY] decimal(18,5)  NULL,
    [INITIAL_EQUITY] decimal(18,5)  NULL,
    [IS_DELETED] bit  NULL,
    [LAST_MODIFIED] datetime  NULL
);
GO

-- Creating table 'BALANCE_SHEET_TRANSACTION'
CREATE TABLE [dbo].[BALANCE_SHEET_TRANSACTION] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [TRANSACTION_STATUS] int  NULL,
    [BALANCE_SHEET_LINK_ID] int  NULL,
    [TRANSACTION_AMOUNT] decimal(18,5)  NULL,
    [TRANSACTION_NAME] nvarchar(max)  NULL,
    [TRANSACTION_TYPE] int  NULL,
    [TRANSACTION_JSON] nvarchar(max)  NULL,
    [IS_DELETED] bit  NULL,
    [DATE_TIME_INSERTED] datetime  NULL,
    [REVENUE_AND_COST_LINK_ID] int  NULL
);
GO

-- Creating table 'CONTENT_MANAGER'
CREATE TABLE [dbo].[CONTENT_MANAGER] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [CONTENT_NAME] nvarchar(500)  NULL,
    [CONTENT_TYPE] nvarchar(500)  NULL,
    [CONTENT_GROUP] nvarchar(500)  NULL,
    [CONTENT_CATEGORY] nvarchar(500)  NULL,
    [CONTENT_THUMBNAIL] varchar(max)  NULL,
    [IMAGE_STRING_ID_LINK] int  NULL,
    [IS_DELETED] bit  NULL,
    [PERSONNEL_LINK_ID] int  NULL,
    [CREATED_DATE_TIME] datetime  NULL,
    [EDIT_DATE_TIME] datetime  NULL,
    [NOTES] nvarchar(max)  NULL,
    [CONTENT_MANAGER_TYPE] int  NULL,
    [FILE_STORAGE_LINK_ID] int  NULL,
    [AUDIO_STORAGE_LINK_ID] int  NULL,
    [VIDEO_STORAGE_LINK_ID] int  NULL,
    [PARENT_VERSION_LINK_ID] int  NULL,
    [VERSION_NUMBER] nvarchar(500)  NULL,
    [IS_ARCHIVED] bit  NULL,
    [IS_DEFAULT] bit  NULL
);
GO

-- Creating table 'FILE_STORAGE'
CREATE TABLE [dbo].[FILE_STORAGE] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [FILE_NAME] nvarchar(200)  NULL,
    [DIRECTORY] nvarchar(800)  NULL,
    [DATABASE_TABLE] smallint  NULL,
    [DATABASE_TABLE_ID] int  NULL,
    [SALES_SCHEDULING_ID] int  NULL,
    [IS_DELETED] bit  NULL,
    [FILE_STRING] nvarchar(max)  NULL
);
GO

-- Creating table 'FINANCE_DECISIONS'
CREATE TABLE [dbo].[FINANCE_DECISIONS] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [ST_LOAN] decimal(18,0)  NULL,
    [LT_LOAN] decimal(18,0)  NULL,
    [FIRM_LINK_ID] int  NULL,
    [PERIOD_LINK_ID] int  NULL,
    [USER_LINK_ID] int  NULL,
    [IS_DELETED] bit  NULL
);
GO

-- Creating table 'GAMEs'
CREATE TABLE [dbo].[GAMEs] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [GAME_NAME] nvarchar(max)  NULL,
    [GAME_TYPE_LINK_ID] int  NULL,
    [IS_DELETED] bit  NULL,
    [IMAGE_MANAGER_LINK_ID] int  NULL,
    [STATUS] int  NULL,
    [GAME_PASSWORD] nvarchar(500)  NULL,
    [DESCRIPTION] nvarchar(max)  NULL
);
GO

-- Creating table 'GAME_FIRM'
CREATE TABLE [dbo].[GAME_FIRM] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [FIRM_NAME] nvarchar(max)  NULL,
    [GAME_LINK_ID] int  NULL,
    [IS_DELETED] bit  NULL,
    [DESCRIPTION] nvarchar(max)  NULL,
    [MAX_NUMBER_OF_PLAYER] int  NULL,
    [BALANCE_SHEET_LINK_ID] int  NULL,
    [PRODUCTION_PRICE] float  NULL,
    [PRODUCTION_QUALITY] int  NULL,
    [MARKET_SHARE] float  NULL,
    [MARKET_SHARE_QTY] int  NULL,
    [MARKET_INFO_LINK_ID] int  NULL,
    [ALPHA_VALUE] float  NULL,
    [PRODUCTION_COST] float  NULL,
    [ST_LOAN_LIMIT] int  NULL,
    [LT_LOAN_LIMIT] int  NULL
);
GO

-- Creating table 'GAME_TYPE'
CREATE TABLE [dbo].[GAME_TYPE] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [GAME_TYPE_NAME] nvarchar(max)  NULL,
    [IS_DELETED] bit  NULL,
    [IMAGE_MANAGER_LINK_ID] int  NULL,
    [DESCRIPTION] nvarchar(max)  NULL
);
GO

-- Creating table 'IMAGE_STRING'
CREATE TABLE [dbo].[IMAGE_STRING] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [NAME] varchar(500)  NULL,
    [IMAGE_HEX_STRING] varchar(max)  NULL,
    [IS_DELETED] bit  NULL,
    [IMAGE_STRING_ID_FOR_INTERNAL_REFERENCE_TO_UNDO_AND_REDO] int  NULL
);
GO

-- Creating table 'INCOME_STATEMENT'
CREATE TABLE [dbo].[INCOME_STATEMENT] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [REVENUE_JSON] float  NULL,
    [COST_JSON] float  NULL,
    [PROFIT] float  NULL,
    [FIRM_LINK_ID] int  NULL,
    [PERIOD_LINK_ID] int  NULL
);
GO

-- Creating table 'MARKET_INFO'
CREATE TABLE [dbo].[MARKET_INFO] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [MARKET_SIZE] decimal(18,5)  NULL,
    [GROWTH_RATE] decimal(18,5)  NULL,
    [VARIATION_TYPE] nvarchar(50)  NULL,
    [VARIATION_SD] decimal(18,5)  NULL,
    [INITIAL_QUALITY] decimal(18,5)  NULL,
    [VARIATION_PARAM_1] decimal(18,5)  NULL,
    [VARIATION_PARAM_2] decimal(18,5)  NULL,
    [VARIATION_PARAM_3] decimal(18,5)  NULL,
    [IS_DELETED] bit  NULL,
    [ALPHA] decimal(18,5)  NULL,
    [BETA] decimal(18,5)  NULL
);
GO

-- Creating table 'MARKETING_DECISIONS'
CREATE TABLE [dbo].[MARKETING_DECISIONS] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [PRICE] decimal(18,5)  NULL,
    [IN_GAME_TIME_IN_DAY] decimal(18,5)  NULL,
    [FIRM_LINK_ID] int  NULL,
    [PERIOD_LINK_ID] int  NULL,
    [USER_LINK_ID] int  NULL,
    [IS_DELETED] bit  NULL
);
GO

-- Creating table 'PERIODs'
CREATE TABLE [dbo].[PERIODs] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [PERIOD_NAME] nvarchar(max)  NULL,
    [PERIOD_NUMBER] int  NULL,
    [STATUS] int  NULL,
    [START_TIME] datetime  NULL,
    [END_TIME] datetime  NULL,
    [IS_DELETED] bit  NULL,
    [EXPECTED_START] datetime  NULL,
    [EXPECTED_END] datetime  NULL,
    [SIMULATION_DURATION] decimal(18,5)  NULL,
    [GAME_LINK_ID] int  NULL
);
GO

-- Creating table 'PRODUCTION_DECISIONS'
CREATE TABLE [dbo].[PRODUCTION_DECISIONS] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [QUANTITY] int  NULL,
    [FIRM_LINK_ID] int  NULL,
    [PERIOD_LINK_ID] int  NULL,
    [IN_GAME_TIME_IN_DAY] decimal(18,5)  NULL,
    [USER_LINK_ID] int  NULL,
    [REVENUE_AND_COST_LINK_ID] int  NULL,
    [IS_DELETED] bit  NULL
);
GO

-- Creating table 'RESULTs'
CREATE TABLE [dbo].[RESULTs] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [MARKETING_DECISION_LINK_ID] int  NULL,
    [PRODUCTION_DECISION_LINK_ID] int  NULL,
    [RND_DECISION_LINK_ID] int  NULL,
    [FINANCE_DECISION_LINK_ID] int  NULL,
    [QUALITY_CHANGE] decimal(18,5)  NULL,
    [MARKET_SHARE_CHANGE] decimal(18,5)  NULL,
    [ACTION_FIRM_LINK_ID] int  NULL,
    [PERIOD_LINK_ID] int  NULL,
    [IN_GAME_TIME_IN_DAY] decimal(18,5)  NULL,
    [IS_DELETED] bit  NULL,
    [TARGET_FIRM_ID] int  NULL,
    [PRODUCTION_COST_CHANGE] decimal(18,5)  NULL
);
GO

-- Creating table 'REVENUE_AND_COST'
CREATE TABLE [dbo].[REVENUE_AND_COST] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [FLOW_TYPE] int  NULL,
    [PAYMENT_TYPE] int  NULL,
    [RECURSIVE_DURATION] int  NULL,
    [PAYMENT_AMOUNT] decimal(18,5)  NULL,
    [NAME] nvarchar(500)  NULL,
    [PARENT_REVENUE_AND_COST_LINK_ID] int  NULL,
    [DESCRIPTION] nvarchar(max)  NULL,
    [FIRM_LINK_ID] int  NULL,
    [PERIOD_LINK_ID] int  NULL,
    [IS_DELETED] bit  NULL,
    [PERIOD_NUMBER] int  NULL,
    [TARGET_TYPE] int  NULL,
    [FIRST_PAYMENT_DATE] decimal(18,5)  NULL,
    [BUSINESS_ASPECT] int  NULL
);
GO

-- Creating table 'RND_DECISIONS'
CREATE TABLE [dbo].[RND_DECISIONS] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [FIRM_LINK_ID] int  NULL,
    [PERIOD_LINK_ID] int  NULL,
    [USER_LINK_ID] int  NULL,
    [REVENUE_AND_COST_LINK_ID] int  NULL,
    [IS_DELETED] bit  NULL
);
GO

-- Creating table 'USERs'
CREATE TABLE [dbo].[USERs] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [USER_NAME] varchar(100)  NULL,
    [FIRST_NAME] varchar(100)  NULL,
    [LAST_NAME] varchar(100)  NULL,
    [POSITION] varchar(100)  NULL,
    [DEPARTMENT] varchar(100)  NULL,
    [GROUP] varchar(100)  NULL,
    [MOBILE_PERSONAL] varchar(50)  NULL,
    [MOBILE_OFFICE] varchar(50)  NULL,
    [LAND_LINE_OFFICE] varchar(50)  NULL,
    [LAND_LINE_HOME] varchar(50)  NULL,
    [EMAIL_PRIMARY] varchar(200)  NULL,
    [EMAIL_SECONDARY] varchar(200)  NULL,
    [SECURITY_LEVEL] smallint  NULL,
    [LOGIN_ALLOWED] bit  NULL,
    [PASSWORD_HASH] varchar(200)  NULL,
    [PASSWORD_SALT] varchar(200)  NULL,
    [IS_AVAILABLE] bit  NULL,
    [IS_DELETED] bit  NULL,
    [PIN_NUMBER_HASH] varchar(200)  NULL,
    [PIN_NUMBER_SALT] varchar(max)  NULL,
    [IMAGE_MANAGER_LINK_ID] int  NULL
);
GO

-- Creating table 'USER_ROLE'
CREATE TABLE [dbo].[USER_ROLE] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [USER_ROLE_NAME] nvarchar(max)  NULL,
    [AUTHORIZATION_LEVEL] int  NULL,
    [IS_DELETED] bit  NULL
);
GO

-- Creating table 'USER_USER_ROLE_GAME_FIRM_RELATIONSHIP'
CREATE TABLE [dbo].[USER_USER_ROLE_GAME_FIRM_RELATIONSHIP] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [USER_LINK_ID] int  NULL,
    [USER_ROLE_LINK_ID] int  NULL,
    [GAME_LINK_ID] int  NULL,
    [FIRM_LINK_ID] int  NULL,
    [IS_DELETED] bit  NULL
);
GO

-- Creating table 'VIDEO_STORAGE'
CREATE TABLE [dbo].[VIDEO_STORAGE] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [NAME] nvarchar(500)  NULL,
    [VIDEO_STRING] nvarchar(max)  NULL,
    [IS_DELETED] bit  NULL
);
GO

-- Creating table 'WEB_API_AUTHORIZATION'
CREATE TABLE [dbo].[WEB_API_AUTHORIZATION] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [LOGGED_IN_PERSONNEL_LINK_ID] int  NULL,
    [LOGGED_IN_DATE_TIME] datetime  NULL,
    [UNIQUE_TOKEN] nvarchar(max)  NULL,
    [EXPIRE_DATE_TIME] datetime  NULL,
    [LAST_REQUESTED_DATE_TIME] datetime  NULL,
    [REQUEST_COUNT] int  NULL,
    [IS_DELETED] bit  NULL
);
GO

-- Creating table 'WEB_API_TRANSACTION'
CREATE TABLE [dbo].[WEB_API_TRANSACTION] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [WEB_API_AUTHORIZATION_LINK_ID] int  NULL,
    [TRANSACTION_URL] nvarchar(max)  NULL,
    [TRANSACTION_DATE_TIME] nvarchar(max)  NULL,
    [TRANSACTION_TYPE] int  NULL,
    [TRANSACTION_HEADERS] nvarchar(max)  NULL,
    [TRANSACTION_BODY] nvarchar(max)  NULL,
    [USER_AGENT] nvarchar(max)  NULL,
    [SERVER_VARIABLES] nvarchar(max)  NULL
);
GO

-- --------------------------------------------------
-- Creating all PRIMARY KEY constraints
-- --------------------------------------------------

-- Creating primary key on [ID] in table 'ACTION_TRANSACTIONS'
ALTER TABLE [dbo].[ACTION_TRANSACTIONS]
ADD CONSTRAINT [PK_ACTION_TRANSACTIONS]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'APP_DEVICES'
ALTER TABLE [dbo].[APP_DEVICES]
ADD CONSTRAINT [PK_APP_DEVICES]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'AUDIO_STORAGE'
ALTER TABLE [dbo].[AUDIO_STORAGE]
ADD CONSTRAINT [PK_AUDIO_STORAGE]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'BALANCE_SHEET'
ALTER TABLE [dbo].[BALANCE_SHEET]
ADD CONSTRAINT [PK_BALANCE_SHEET]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'BALANCE_SHEET_TRANSACTION'
ALTER TABLE [dbo].[BALANCE_SHEET_TRANSACTION]
ADD CONSTRAINT [PK_BALANCE_SHEET_TRANSACTION]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'CONTENT_MANAGER'
ALTER TABLE [dbo].[CONTENT_MANAGER]
ADD CONSTRAINT [PK_CONTENT_MANAGER]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'FILE_STORAGE'
ALTER TABLE [dbo].[FILE_STORAGE]
ADD CONSTRAINT [PK_FILE_STORAGE]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'FINANCE_DECISIONS'
ALTER TABLE [dbo].[FINANCE_DECISIONS]
ADD CONSTRAINT [PK_FINANCE_DECISIONS]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'GAMEs'
ALTER TABLE [dbo].[GAMEs]
ADD CONSTRAINT [PK_GAMEs]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'GAME_FIRM'
ALTER TABLE [dbo].[GAME_FIRM]
ADD CONSTRAINT [PK_GAME_FIRM]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'GAME_TYPE'
ALTER TABLE [dbo].[GAME_TYPE]
ADD CONSTRAINT [PK_GAME_TYPE]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'IMAGE_STRING'
ALTER TABLE [dbo].[IMAGE_STRING]
ADD CONSTRAINT [PK_IMAGE_STRING]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'INCOME_STATEMENT'
ALTER TABLE [dbo].[INCOME_STATEMENT]
ADD CONSTRAINT [PK_INCOME_STATEMENT]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'MARKET_INFO'
ALTER TABLE [dbo].[MARKET_INFO]
ADD CONSTRAINT [PK_MARKET_INFO]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'MARKETING_DECISIONS'
ALTER TABLE [dbo].[MARKETING_DECISIONS]
ADD CONSTRAINT [PK_MARKETING_DECISIONS]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'PERIODs'
ALTER TABLE [dbo].[PERIODs]
ADD CONSTRAINT [PK_PERIODs]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'PRODUCTION_DECISIONS'
ALTER TABLE [dbo].[PRODUCTION_DECISIONS]
ADD CONSTRAINT [PK_PRODUCTION_DECISIONS]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'RESULTs'
ALTER TABLE [dbo].[RESULTs]
ADD CONSTRAINT [PK_RESULTs]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'REVENUE_AND_COST'
ALTER TABLE [dbo].[REVENUE_AND_COST]
ADD CONSTRAINT [PK_REVENUE_AND_COST]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'RND_DECISIONS'
ALTER TABLE [dbo].[RND_DECISIONS]
ADD CONSTRAINT [PK_RND_DECISIONS]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'USERs'
ALTER TABLE [dbo].[USERs]
ADD CONSTRAINT [PK_USERs]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'USER_ROLE'
ALTER TABLE [dbo].[USER_ROLE]
ADD CONSTRAINT [PK_USER_ROLE]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'USER_USER_ROLE_GAME_FIRM_RELATIONSHIP'
ALTER TABLE [dbo].[USER_USER_ROLE_GAME_FIRM_RELATIONSHIP]
ADD CONSTRAINT [PK_USER_USER_ROLE_GAME_FIRM_RELATIONSHIP]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'VIDEO_STORAGE'
ALTER TABLE [dbo].[VIDEO_STORAGE]
ADD CONSTRAINT [PK_VIDEO_STORAGE]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'WEB_API_AUTHORIZATION'
ALTER TABLE [dbo].[WEB_API_AUTHORIZATION]
ADD CONSTRAINT [PK_WEB_API_AUTHORIZATION]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID] in table 'WEB_API_TRANSACTION'
ALTER TABLE [dbo].[WEB_API_TRANSACTION]
ADD CONSTRAINT [PK_WEB_API_TRANSACTION]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- --------------------------------------------------
-- Creating all FOREIGN KEY constraints
-- --------------------------------------------------

-- Creating foreign key on [DEVICE_LINK_ID] in table 'ACTION_TRANSACTIONS'
ALTER TABLE [dbo].[ACTION_TRANSACTIONS]
ADD CONSTRAINT [FK_ARC_APP_ACTION_TRANSACTIONS_ARC_APP_DEVICES]
    FOREIGN KEY ([DEVICE_LINK_ID])
    REFERENCES [dbo].[APP_DEVICES]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ARC_APP_ACTION_TRANSACTIONS_ARC_APP_DEVICES'
CREATE INDEX [IX_FK_ARC_APP_ACTION_TRANSACTIONS_ARC_APP_DEVICES]
ON [dbo].[ACTION_TRANSACTIONS]
    ([DEVICE_LINK_ID]);
GO

-- Creating foreign key on [PERSONNEL_LINK_ID] in table 'ACTION_TRANSACTIONS'
ALTER TABLE [dbo].[ACTION_TRANSACTIONS]
ADD CONSTRAINT [FK_ARC_APP_ACTION_TRANSACTIONS_PERSONNEL]
    FOREIGN KEY ([PERSONNEL_LINK_ID])
    REFERENCES [dbo].[USERs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ARC_APP_ACTION_TRANSACTIONS_PERSONNEL'
CREATE INDEX [IX_FK_ARC_APP_ACTION_TRANSACTIONS_PERSONNEL]
ON [dbo].[ACTION_TRANSACTIONS]
    ([PERSONNEL_LINK_ID]);
GO

-- Creating foreign key on [PERSONNEL_LINK_ID] in table 'APP_DEVICES'
ALTER TABLE [dbo].[APP_DEVICES]
ADD CONSTRAINT [FK_ARC_APP_DEVICES_PERSONNEL]
    FOREIGN KEY ([PERSONNEL_LINK_ID])
    REFERENCES [dbo].[USERs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ARC_APP_DEVICES_PERSONNEL'
CREATE INDEX [IX_FK_ARC_APP_DEVICES_PERSONNEL]
ON [dbo].[APP_DEVICES]
    ([PERSONNEL_LINK_ID]);
GO

-- Creating foreign key on [AUDIO_STORAGE_LINK_ID] in table 'CONTENT_MANAGER'
ALTER TABLE [dbo].[CONTENT_MANAGER]
ADD CONSTRAINT [FK_CONTENT_MANAGER_AUDIO_STORAGE]
    FOREIGN KEY ([AUDIO_STORAGE_LINK_ID])
    REFERENCES [dbo].[AUDIO_STORAGE]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CONTENT_MANAGER_AUDIO_STORAGE'
CREATE INDEX [IX_FK_CONTENT_MANAGER_AUDIO_STORAGE]
ON [dbo].[CONTENT_MANAGER]
    ([AUDIO_STORAGE_LINK_ID]);
GO

-- Creating foreign key on [BALANCE_SHEET_LINK_ID] in table 'BALANCE_SHEET_TRANSACTION'
ALTER TABLE [dbo].[BALANCE_SHEET_TRANSACTION]
ADD CONSTRAINT [FK_BALANCE_SHEET_TRANSACTION_BALANCE_SHEET]
    FOREIGN KEY ([BALANCE_SHEET_LINK_ID])
    REFERENCES [dbo].[BALANCE_SHEET]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_BALANCE_SHEET_TRANSACTION_BALANCE_SHEET'
CREATE INDEX [IX_FK_BALANCE_SHEET_TRANSACTION_BALANCE_SHEET]
ON [dbo].[BALANCE_SHEET_TRANSACTION]
    ([BALANCE_SHEET_LINK_ID]);
GO

-- Creating foreign key on [BALANCE_SHEET_LINK_ID] in table 'GAME_FIRM'
ALTER TABLE [dbo].[GAME_FIRM]
ADD CONSTRAINT [FK_GAME_FIRM_BALANCE_SHEET]
    FOREIGN KEY ([BALANCE_SHEET_LINK_ID])
    REFERENCES [dbo].[BALANCE_SHEET]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_GAME_FIRM_BALANCE_SHEET'
CREATE INDEX [IX_FK_GAME_FIRM_BALANCE_SHEET]
ON [dbo].[GAME_FIRM]
    ([BALANCE_SHEET_LINK_ID]);
GO

-- Creating foreign key on [REVENUE_AND_COST_LINK_ID] in table 'BALANCE_SHEET_TRANSACTION'
ALTER TABLE [dbo].[BALANCE_SHEET_TRANSACTION]
ADD CONSTRAINT [FK_BALANCE_SHEET_TRANSACTION_REVENUE_AND_COST]
    FOREIGN KEY ([REVENUE_AND_COST_LINK_ID])
    REFERENCES [dbo].[REVENUE_AND_COST]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_BALANCE_SHEET_TRANSACTION_REVENUE_AND_COST'
CREATE INDEX [IX_FK_BALANCE_SHEET_TRANSACTION_REVENUE_AND_COST]
ON [dbo].[BALANCE_SHEET_TRANSACTION]
    ([REVENUE_AND_COST_LINK_ID]);
GO

-- Creating foreign key on [PARENT_VERSION_LINK_ID] in table 'CONTENT_MANAGER'
ALTER TABLE [dbo].[CONTENT_MANAGER]
ADD CONSTRAINT [FK_CONTENT_MANAGER_CONTENT_MANAGER]
    FOREIGN KEY ([PARENT_VERSION_LINK_ID])
    REFERENCES [dbo].[CONTENT_MANAGER]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CONTENT_MANAGER_CONTENT_MANAGER'
CREATE INDEX [IX_FK_CONTENT_MANAGER_CONTENT_MANAGER]
ON [dbo].[CONTENT_MANAGER]
    ([PARENT_VERSION_LINK_ID]);
GO

-- Creating foreign key on [FILE_STORAGE_LINK_ID] in table 'CONTENT_MANAGER'
ALTER TABLE [dbo].[CONTENT_MANAGER]
ADD CONSTRAINT [FK_CONTENT_MANAGER_FILE_STORAGE]
    FOREIGN KEY ([FILE_STORAGE_LINK_ID])
    REFERENCES [dbo].[FILE_STORAGE]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CONTENT_MANAGER_FILE_STORAGE'
CREATE INDEX [IX_FK_CONTENT_MANAGER_FILE_STORAGE]
ON [dbo].[CONTENT_MANAGER]
    ([FILE_STORAGE_LINK_ID]);
GO

-- Creating foreign key on [VIDEO_STORAGE_LINK_ID] in table 'CONTENT_MANAGER'
ALTER TABLE [dbo].[CONTENT_MANAGER]
ADD CONSTRAINT [FK_CONTENT_MANAGER_VIDEO_STORAGE]
    FOREIGN KEY ([VIDEO_STORAGE_LINK_ID])
    REFERENCES [dbo].[VIDEO_STORAGE]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CONTENT_MANAGER_VIDEO_STORAGE'
CREATE INDEX [IX_FK_CONTENT_MANAGER_VIDEO_STORAGE]
ON [dbo].[CONTENT_MANAGER]
    ([VIDEO_STORAGE_LINK_ID]);
GO

-- Creating foreign key on [IMAGE_MANAGER_LINK_ID] in table 'GAMEs'
ALTER TABLE [dbo].[GAMEs]
ADD CONSTRAINT [FK_GAME_CONTENT_MANAGER]
    FOREIGN KEY ([IMAGE_MANAGER_LINK_ID])
    REFERENCES [dbo].[CONTENT_MANAGER]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_GAME_CONTENT_MANAGER'
CREATE INDEX [IX_FK_GAME_CONTENT_MANAGER]
ON [dbo].[GAMEs]
    ([IMAGE_MANAGER_LINK_ID]);
GO

-- Creating foreign key on [IMAGE_MANAGER_LINK_ID] in table 'GAME_TYPE'
ALTER TABLE [dbo].[GAME_TYPE]
ADD CONSTRAINT [FK_GAME_TYPE_CONTENT_MANAGER]
    FOREIGN KEY ([IMAGE_MANAGER_LINK_ID])
    REFERENCES [dbo].[CONTENT_MANAGER]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_GAME_TYPE_CONTENT_MANAGER'
CREATE INDEX [IX_FK_GAME_TYPE_CONTENT_MANAGER]
ON [dbo].[GAME_TYPE]
    ([IMAGE_MANAGER_LINK_ID]);
GO

-- Creating foreign key on [IMAGE_STRING_ID_LINK] in table 'CONTENT_MANAGER'
ALTER TABLE [dbo].[CONTENT_MANAGER]
ADD CONSTRAINT [FK_IMAGE_STRING_MANAGER_IMAGE_STRING]
    FOREIGN KEY ([IMAGE_STRING_ID_LINK])
    REFERENCES [dbo].[IMAGE_STRING]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_IMAGE_STRING_MANAGER_IMAGE_STRING'
CREATE INDEX [IX_FK_IMAGE_STRING_MANAGER_IMAGE_STRING]
ON [dbo].[CONTENT_MANAGER]
    ([IMAGE_STRING_ID_LINK]);
GO

-- Creating foreign key on [PERSONNEL_LINK_ID] in table 'CONTENT_MANAGER'
ALTER TABLE [dbo].[CONTENT_MANAGER]
ADD CONSTRAINT [FK_IMAGE_STRING_MANAGER_PERSONNEL]
    FOREIGN KEY ([PERSONNEL_LINK_ID])
    REFERENCES [dbo].[USERs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_IMAGE_STRING_MANAGER_PERSONNEL'
CREATE INDEX [IX_FK_IMAGE_STRING_MANAGER_PERSONNEL]
ON [dbo].[CONTENT_MANAGER]
    ([PERSONNEL_LINK_ID]);
GO

-- Creating foreign key on [IMAGE_MANAGER_LINK_ID] in table 'USERs'
ALTER TABLE [dbo].[USERs]
ADD CONSTRAINT [FK_USER_CONTENT_MANAGER]
    FOREIGN KEY ([IMAGE_MANAGER_LINK_ID])
    REFERENCES [dbo].[CONTENT_MANAGER]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_USER_CONTENT_MANAGER'
CREATE INDEX [IX_FK_USER_CONTENT_MANAGER]
ON [dbo].[USERs]
    ([IMAGE_MANAGER_LINK_ID]);
GO

-- Creating foreign key on [FINANCE_DECISION_LINK_ID] in table 'RESULTs'
ALTER TABLE [dbo].[RESULTs]
ADD CONSTRAINT [FK_RESULT_FINANCE_DECISIONS]
    FOREIGN KEY ([FINANCE_DECISION_LINK_ID])
    REFERENCES [dbo].[FINANCE_DECISIONS]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_RESULT_FINANCE_DECISIONS'
CREATE INDEX [IX_FK_RESULT_FINANCE_DECISIONS]
ON [dbo].[RESULTs]
    ([FINANCE_DECISION_LINK_ID]);
GO

-- Creating foreign key on [GAME_LINK_ID] in table 'GAME_FIRM'
ALTER TABLE [dbo].[GAME_FIRM]
ADD CONSTRAINT [FK_GAME_FIRM_GAME]
    FOREIGN KEY ([GAME_LINK_ID])
    REFERENCES [dbo].[GAMEs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_GAME_FIRM_GAME'
CREATE INDEX [IX_FK_GAME_FIRM_GAME]
ON [dbo].[GAME_FIRM]
    ([GAME_LINK_ID]);
GO

-- Creating foreign key on [GAME_TYPE_LINK_ID] in table 'GAMEs'
ALTER TABLE [dbo].[GAMEs]
ADD CONSTRAINT [FK_GAME_GAME_TYPE]
    FOREIGN KEY ([GAME_TYPE_LINK_ID])
    REFERENCES [dbo].[GAME_TYPE]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_GAME_GAME_TYPE'
CREATE INDEX [IX_FK_GAME_GAME_TYPE]
ON [dbo].[GAMEs]
    ([GAME_TYPE_LINK_ID]);
GO

-- Creating foreign key on [GAME_LINK_ID] in table 'PERIODs'
ALTER TABLE [dbo].[PERIODs]
ADD CONSTRAINT [FK_PERIOD_GAME]
    FOREIGN KEY ([GAME_LINK_ID])
    REFERENCES [dbo].[GAMEs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PERIOD_GAME'
CREATE INDEX [IX_FK_PERIOD_GAME]
ON [dbo].[PERIODs]
    ([GAME_LINK_ID]);
GO

-- Creating foreign key on [GAME_LINK_ID] in table 'USER_USER_ROLE_GAME_FIRM_RELATIONSHIP'
ALTER TABLE [dbo].[USER_USER_ROLE_GAME_FIRM_RELATIONSHIP]
ADD CONSTRAINT [FK_USER_USER_ROLE_GAME_RELATIONSHIP_GAME]
    FOREIGN KEY ([GAME_LINK_ID])
    REFERENCES [dbo].[GAMEs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_USER_USER_ROLE_GAME_RELATIONSHIP_GAME'
CREATE INDEX [IX_FK_USER_USER_ROLE_GAME_RELATIONSHIP_GAME]
ON [dbo].[USER_USER_ROLE_GAME_FIRM_RELATIONSHIP]
    ([GAME_LINK_ID]);
GO

-- Creating foreign key on [MARKET_INFO_LINK_ID] in table 'GAME_FIRM'
ALTER TABLE [dbo].[GAME_FIRM]
ADD CONSTRAINT [FK_GAME_FIRM_MARKET_INFO_GAME_FIRM]
    FOREIGN KEY ([MARKET_INFO_LINK_ID])
    REFERENCES [dbo].[MARKET_INFO]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_GAME_FIRM_MARKET_INFO_GAME_FIRM'
CREATE INDEX [IX_FK_GAME_FIRM_MARKET_INFO_GAME_FIRM]
ON [dbo].[GAME_FIRM]
    ([MARKET_INFO_LINK_ID]);
GO

-- Creating foreign key on [FIRM_LINK_ID] in table 'INCOME_STATEMENT'
ALTER TABLE [dbo].[INCOME_STATEMENT]
ADD CONSTRAINT [FK_INCOME_STATEMENT_FIRM_INCOME_STATEMENT]
    FOREIGN KEY ([FIRM_LINK_ID])
    REFERENCES [dbo].[GAME_FIRM]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_INCOME_STATEMENT_FIRM_INCOME_STATEMENT'
CREATE INDEX [IX_FK_INCOME_STATEMENT_FIRM_INCOME_STATEMENT]
ON [dbo].[INCOME_STATEMENT]
    ([FIRM_LINK_ID]);
GO

-- Creating foreign key on [FIRM_LINK_ID] in table 'MARKETING_DECISIONS'
ALTER TABLE [dbo].[MARKETING_DECISIONS]
ADD CONSTRAINT [FK_MARKETING_DECISIONS_GAME_FIRM]
    FOREIGN KEY ([FIRM_LINK_ID])
    REFERENCES [dbo].[GAME_FIRM]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_MARKETING_DECISIONS_GAME_FIRM'
CREATE INDEX [IX_FK_MARKETING_DECISIONS_GAME_FIRM]
ON [dbo].[MARKETING_DECISIONS]
    ([FIRM_LINK_ID]);
GO

-- Creating foreign key on [FIRM_LINK_ID] in table 'PRODUCTION_DECISIONS'
ALTER TABLE [dbo].[PRODUCTION_DECISIONS]
ADD CONSTRAINT [FK_PRODUCTION_DECISIONS_GAME_FIRM]
    FOREIGN KEY ([FIRM_LINK_ID])
    REFERENCES [dbo].[GAME_FIRM]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PRODUCTION_DECISIONS_GAME_FIRM'
CREATE INDEX [IX_FK_PRODUCTION_DECISIONS_GAME_FIRM]
ON [dbo].[PRODUCTION_DECISIONS]
    ([FIRM_LINK_ID]);
GO

-- Creating foreign key on [ACTION_FIRM_LINK_ID] in table 'RESULTs'
ALTER TABLE [dbo].[RESULTs]
ADD CONSTRAINT [FK_RESULT_GAME_FIRM]
    FOREIGN KEY ([ACTION_FIRM_LINK_ID])
    REFERENCES [dbo].[GAME_FIRM]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_RESULT_GAME_FIRM'
CREATE INDEX [IX_FK_RESULT_GAME_FIRM]
ON [dbo].[RESULTs]
    ([ACTION_FIRM_LINK_ID]);
GO

-- Creating foreign key on [TARGET_FIRM_ID] in table 'RESULTs'
ALTER TABLE [dbo].[RESULTs]
ADD CONSTRAINT [FK_RESULT_GAME_FIRM1]
    FOREIGN KEY ([TARGET_FIRM_ID])
    REFERENCES [dbo].[GAME_FIRM]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_RESULT_GAME_FIRM1'
CREATE INDEX [IX_FK_RESULT_GAME_FIRM1]
ON [dbo].[RESULTs]
    ([TARGET_FIRM_ID]);
GO

-- Creating foreign key on [FIRM_LINK_ID] in table 'REVENUE_AND_COST'
ALTER TABLE [dbo].[REVENUE_AND_COST]
ADD CONSTRAINT [FK_REVENUE_AND_COST_GAME_FIRM]
    FOREIGN KEY ([FIRM_LINK_ID])
    REFERENCES [dbo].[GAME_FIRM]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_REVENUE_AND_COST_GAME_FIRM'
CREATE INDEX [IX_FK_REVENUE_AND_COST_GAME_FIRM]
ON [dbo].[REVENUE_AND_COST]
    ([FIRM_LINK_ID]);
GO

-- Creating foreign key on [FIRM_LINK_ID] in table 'RND_DECISIONS'
ALTER TABLE [dbo].[RND_DECISIONS]
ADD CONSTRAINT [FK_RND_DECISIONS_GAME_FIRM]
    FOREIGN KEY ([FIRM_LINK_ID])
    REFERENCES [dbo].[GAME_FIRM]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_RND_DECISIONS_GAME_FIRM'
CREATE INDEX [IX_FK_RND_DECISIONS_GAME_FIRM]
ON [dbo].[RND_DECISIONS]
    ([FIRM_LINK_ID]);
GO

-- Creating foreign key on [FIRM_LINK_ID] in table 'USER_USER_ROLE_GAME_FIRM_RELATIONSHIP'
ALTER TABLE [dbo].[USER_USER_ROLE_GAME_FIRM_RELATIONSHIP]
ADD CONSTRAINT [FK_USER_USER_ROLE_GAME_RELATIONSHIP_GAME_FIRM]
    FOREIGN KEY ([FIRM_LINK_ID])
    REFERENCES [dbo].[GAME_FIRM]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_USER_USER_ROLE_GAME_RELATIONSHIP_GAME_FIRM'
CREATE INDEX [IX_FK_USER_USER_ROLE_GAME_RELATIONSHIP_GAME_FIRM]
ON [dbo].[USER_USER_ROLE_GAME_FIRM_RELATIONSHIP]
    ([FIRM_LINK_ID]);
GO

-- Creating foreign key on [PERIOD_LINK_ID] in table 'INCOME_STATEMENT'
ALTER TABLE [dbo].[INCOME_STATEMENT]
ADD CONSTRAINT [FK_INCOME_STATEMENT_PERIOD_INCOME_STATEMENT]
    FOREIGN KEY ([PERIOD_LINK_ID])
    REFERENCES [dbo].[PERIODs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_INCOME_STATEMENT_PERIOD_INCOME_STATEMENT'
CREATE INDEX [IX_FK_INCOME_STATEMENT_PERIOD_INCOME_STATEMENT]
ON [dbo].[INCOME_STATEMENT]
    ([PERIOD_LINK_ID]);
GO

-- Creating foreign key on [PERIOD_LINK_ID] in table 'MARKETING_DECISIONS'
ALTER TABLE [dbo].[MARKETING_DECISIONS]
ADD CONSTRAINT [FK_MARKETING_DECISIONS_PERIOD]
    FOREIGN KEY ([PERIOD_LINK_ID])
    REFERENCES [dbo].[PERIODs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_MARKETING_DECISIONS_PERIOD'
CREATE INDEX [IX_FK_MARKETING_DECISIONS_PERIOD]
ON [dbo].[MARKETING_DECISIONS]
    ([PERIOD_LINK_ID]);
GO

-- Creating foreign key on [USER_LINK_ID] in table 'MARKETING_DECISIONS'
ALTER TABLE [dbo].[MARKETING_DECISIONS]
ADD CONSTRAINT [FK_MARKETING_DECISIONS_USER]
    FOREIGN KEY ([USER_LINK_ID])
    REFERENCES [dbo].[USERs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_MARKETING_DECISIONS_USER'
CREATE INDEX [IX_FK_MARKETING_DECISIONS_USER]
ON [dbo].[MARKETING_DECISIONS]
    ([USER_LINK_ID]);
GO

-- Creating foreign key on [MARKETING_DECISION_LINK_ID] in table 'RESULTs'
ALTER TABLE [dbo].[RESULTs]
ADD CONSTRAINT [FK_RESULT_MARKETING_DECISIONS]
    FOREIGN KEY ([MARKETING_DECISION_LINK_ID])
    REFERENCES [dbo].[MARKETING_DECISIONS]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_RESULT_MARKETING_DECISIONS'
CREATE INDEX [IX_FK_RESULT_MARKETING_DECISIONS]
ON [dbo].[RESULTs]
    ([MARKETING_DECISION_LINK_ID]);
GO

-- Creating foreign key on [PERIOD_LINK_ID] in table 'PRODUCTION_DECISIONS'
ALTER TABLE [dbo].[PRODUCTION_DECISIONS]
ADD CONSTRAINT [FK_PRODUCTION_DECISIONS_PERIOD]
    FOREIGN KEY ([PERIOD_LINK_ID])
    REFERENCES [dbo].[PERIODs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PRODUCTION_DECISIONS_PERIOD'
CREATE INDEX [IX_FK_PRODUCTION_DECISIONS_PERIOD]
ON [dbo].[PRODUCTION_DECISIONS]
    ([PERIOD_LINK_ID]);
GO

-- Creating foreign key on [PERIOD_LINK_ID] in table 'RESULTs'
ALTER TABLE [dbo].[RESULTs]
ADD CONSTRAINT [FK_RESULT_PERIOD]
    FOREIGN KEY ([PERIOD_LINK_ID])
    REFERENCES [dbo].[PERIODs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_RESULT_PERIOD'
CREATE INDEX [IX_FK_RESULT_PERIOD]
ON [dbo].[RESULTs]
    ([PERIOD_LINK_ID]);
GO

-- Creating foreign key on [PERIOD_LINK_ID] in table 'REVENUE_AND_COST'
ALTER TABLE [dbo].[REVENUE_AND_COST]
ADD CONSTRAINT [FK_REVENUE_AND_COST_PERIOD]
    FOREIGN KEY ([PERIOD_LINK_ID])
    REFERENCES [dbo].[PERIODs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_REVENUE_AND_COST_PERIOD'
CREATE INDEX [IX_FK_REVENUE_AND_COST_PERIOD]
ON [dbo].[REVENUE_AND_COST]
    ([PERIOD_LINK_ID]);
GO

-- Creating foreign key on [PERIOD_LINK_ID] in table 'RND_DECISIONS'
ALTER TABLE [dbo].[RND_DECISIONS]
ADD CONSTRAINT [FK_RND_DECISIONS_PERIOD]
    FOREIGN KEY ([PERIOD_LINK_ID])
    REFERENCES [dbo].[PERIODs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_RND_DECISIONS_PERIOD'
CREATE INDEX [IX_FK_RND_DECISIONS_PERIOD]
ON [dbo].[RND_DECISIONS]
    ([PERIOD_LINK_ID]);
GO

-- Creating foreign key on [REVENUE_AND_COST_LINK_ID] in table 'PRODUCTION_DECISIONS'
ALTER TABLE [dbo].[PRODUCTION_DECISIONS]
ADD CONSTRAINT [FK_PRODUCTION_DECISIONS_REVENUE_AND_COST]
    FOREIGN KEY ([REVENUE_AND_COST_LINK_ID])
    REFERENCES [dbo].[REVENUE_AND_COST]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PRODUCTION_DECISIONS_REVENUE_AND_COST'
CREATE INDEX [IX_FK_PRODUCTION_DECISIONS_REVENUE_AND_COST]
ON [dbo].[PRODUCTION_DECISIONS]
    ([REVENUE_AND_COST_LINK_ID]);
GO

-- Creating foreign key on [USER_LINK_ID] in table 'PRODUCTION_DECISIONS'
ALTER TABLE [dbo].[PRODUCTION_DECISIONS]
ADD CONSTRAINT [FK_PRODUCTION_DECISIONS_USER]
    FOREIGN KEY ([USER_LINK_ID])
    REFERENCES [dbo].[USERs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PRODUCTION_DECISIONS_USER'
CREATE INDEX [IX_FK_PRODUCTION_DECISIONS_USER]
ON [dbo].[PRODUCTION_DECISIONS]
    ([USER_LINK_ID]);
GO

-- Creating foreign key on [PRODUCTION_DECISION_LINK_ID] in table 'RESULTs'
ALTER TABLE [dbo].[RESULTs]
ADD CONSTRAINT [FK_RESULT_PRODUCTION_DECISIONS]
    FOREIGN KEY ([PRODUCTION_DECISION_LINK_ID])
    REFERENCES [dbo].[PRODUCTION_DECISIONS]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_RESULT_PRODUCTION_DECISIONS'
CREATE INDEX [IX_FK_RESULT_PRODUCTION_DECISIONS]
ON [dbo].[RESULTs]
    ([PRODUCTION_DECISION_LINK_ID]);
GO

-- Creating foreign key on [RND_DECISION_LINK_ID] in table 'RESULTs'
ALTER TABLE [dbo].[RESULTs]
ADD CONSTRAINT [FK_RESULT_RND_DECISIONS]
    FOREIGN KEY ([RND_DECISION_LINK_ID])
    REFERENCES [dbo].[RND_DECISIONS]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_RESULT_RND_DECISIONS'
CREATE INDEX [IX_FK_RESULT_RND_DECISIONS]
ON [dbo].[RESULTs]
    ([RND_DECISION_LINK_ID]);
GO

-- Creating foreign key on [PARENT_REVENUE_AND_COST_LINK_ID] in table 'REVENUE_AND_COST'
ALTER TABLE [dbo].[REVENUE_AND_COST]
ADD CONSTRAINT [FK_REVENUE_AND_COST_REVENUE_AND_COST]
    FOREIGN KEY ([PARENT_REVENUE_AND_COST_LINK_ID])
    REFERENCES [dbo].[REVENUE_AND_COST]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_REVENUE_AND_COST_REVENUE_AND_COST'
CREATE INDEX [IX_FK_REVENUE_AND_COST_REVENUE_AND_COST]
ON [dbo].[REVENUE_AND_COST]
    ([PARENT_REVENUE_AND_COST_LINK_ID]);
GO

-- Creating foreign key on [REVENUE_AND_COST_LINK_ID] in table 'RND_DECISIONS'
ALTER TABLE [dbo].[RND_DECISIONS]
ADD CONSTRAINT [FK_RND_DECISIONS_REVENUE_AND_COST]
    FOREIGN KEY ([REVENUE_AND_COST_LINK_ID])
    REFERENCES [dbo].[REVENUE_AND_COST]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_RND_DECISIONS_REVENUE_AND_COST'
CREATE INDEX [IX_FK_RND_DECISIONS_REVENUE_AND_COST]
ON [dbo].[RND_DECISIONS]
    ([REVENUE_AND_COST_LINK_ID]);
GO

-- Creating foreign key on [USER_LINK_ID] in table 'RND_DECISIONS'
ALTER TABLE [dbo].[RND_DECISIONS]
ADD CONSTRAINT [FK_RND_DECISIONS_USER]
    FOREIGN KEY ([USER_LINK_ID])
    REFERENCES [dbo].[USERs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_RND_DECISIONS_USER'
CREATE INDEX [IX_FK_RND_DECISIONS_USER]
ON [dbo].[RND_DECISIONS]
    ([USER_LINK_ID]);
GO

-- Creating foreign key on [USER_LINK_ID] in table 'USER_USER_ROLE_GAME_FIRM_RELATIONSHIP'
ALTER TABLE [dbo].[USER_USER_ROLE_GAME_FIRM_RELATIONSHIP]
ADD CONSTRAINT [FK_USER_USER_ROLE_GAME_RELATIONSHIP_USER]
    FOREIGN KEY ([USER_LINK_ID])
    REFERENCES [dbo].[USERs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_USER_USER_ROLE_GAME_RELATIONSHIP_USER'
CREATE INDEX [IX_FK_USER_USER_ROLE_GAME_RELATIONSHIP_USER]
ON [dbo].[USER_USER_ROLE_GAME_FIRM_RELATIONSHIP]
    ([USER_LINK_ID]);
GO

-- Creating foreign key on [LOGGED_IN_PERSONNEL_LINK_ID] in table 'WEB_API_AUTHORIZATION'
ALTER TABLE [dbo].[WEB_API_AUTHORIZATION]
ADD CONSTRAINT [FK_WEB_API_AUTHORIZATION_PERSONNEL]
    FOREIGN KEY ([LOGGED_IN_PERSONNEL_LINK_ID])
    REFERENCES [dbo].[USERs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_WEB_API_AUTHORIZATION_PERSONNEL'
CREATE INDEX [IX_FK_WEB_API_AUTHORIZATION_PERSONNEL]
ON [dbo].[WEB_API_AUTHORIZATION]
    ([LOGGED_IN_PERSONNEL_LINK_ID]);
GO

-- Creating foreign key on [USER_ROLE_LINK_ID] in table 'USER_USER_ROLE_GAME_FIRM_RELATIONSHIP'
ALTER TABLE [dbo].[USER_USER_ROLE_GAME_FIRM_RELATIONSHIP]
ADD CONSTRAINT [FK_USER_USER_ROLE_GAME_RELATIONSHIP_USER_ROLE]
    FOREIGN KEY ([USER_ROLE_LINK_ID])
    REFERENCES [dbo].[USER_ROLE]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_USER_USER_ROLE_GAME_RELATIONSHIP_USER_ROLE'
CREATE INDEX [IX_FK_USER_USER_ROLE_GAME_RELATIONSHIP_USER_ROLE]
ON [dbo].[USER_USER_ROLE_GAME_FIRM_RELATIONSHIP]
    ([USER_ROLE_LINK_ID]);
GO

-- Creating foreign key on [WEB_API_AUTHORIZATION_LINK_ID] in table 'WEB_API_TRANSACTION'
ALTER TABLE [dbo].[WEB_API_TRANSACTION]
ADD CONSTRAINT [FK_WEB_API_TRANSACTION_WEB_API_AUTHORIZATION]
    FOREIGN KEY ([WEB_API_AUTHORIZATION_LINK_ID])
    REFERENCES [dbo].[WEB_API_AUTHORIZATION]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_WEB_API_TRANSACTION_WEB_API_AUTHORIZATION'
CREATE INDEX [IX_FK_WEB_API_TRANSACTION_WEB_API_AUTHORIZATION]
ON [dbo].[WEB_API_TRANSACTION]
    ([WEB_API_AUTHORIZATION_LINK_ID]);
GO

-- Creating foreign key on [FIRM_LINK_ID] in table 'FINANCE_DECISIONS'
ALTER TABLE [dbo].[FINANCE_DECISIONS]
ADD CONSTRAINT [FK_FINANCE_DECISIONS_FIRM_FINANCE_DECISIONS]
    FOREIGN KEY ([FIRM_LINK_ID])
    REFERENCES [dbo].[GAME_FIRM]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_FINANCE_DECISIONS_FIRM_FINANCE_DECISIONS'
CREATE INDEX [IX_FK_FINANCE_DECISIONS_FIRM_FINANCE_DECISIONS]
ON [dbo].[FINANCE_DECISIONS]
    ([FIRM_LINK_ID]);
GO

-- Creating foreign key on [PERIOD_LINK_ID] in table 'FINANCE_DECISIONS'
ALTER TABLE [dbo].[FINANCE_DECISIONS]
ADD CONSTRAINT [FK_FINANCE_DECISIONS_PERIOD_FINANCE_DECISIONS]
    FOREIGN KEY ([PERIOD_LINK_ID])
    REFERENCES [dbo].[PERIODs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_FINANCE_DECISIONS_PERIOD_FINANCE_DECISIONS'
CREATE INDEX [IX_FK_FINANCE_DECISIONS_PERIOD_FINANCE_DECISIONS]
ON [dbo].[FINANCE_DECISIONS]
    ([PERIOD_LINK_ID]);
GO

-- Creating foreign key on [USER_LINK_ID] in table 'FINANCE_DECISIONS'
ALTER TABLE [dbo].[FINANCE_DECISIONS]
ADD CONSTRAINT [FK_FINANCE_DECISIONS_USER_FINANCE_DECISIONS]
    FOREIGN KEY ([USER_LINK_ID])
    REFERENCES [dbo].[USERs]
        ([ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_FINANCE_DECISIONS_USER_FINANCE_DECISIONS'
CREATE INDEX [IX_FK_FINANCE_DECISIONS_USER_FINANCE_DECISIONS]
ON [dbo].[FINANCE_DECISIONS]
    ([USER_LINK_ID]);
GO

-- --------------------------------------------------
-- Script has ended
-- --------------------------------------------------