'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class FYP_DATABASEEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=FYP_DATABASEEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property ACTION_TRANSACTIONS() As DbSet(Of ACTION_TRANSACTIONS)
    Public Overridable Property APP_DEVICES() As DbSet(Of APP_DEVICES)
    Public Overridable Property AUDIO_STORAGE() As DbSet(Of AUDIO_STORAGE)
    Public Overridable Property BALANCE_SHEET() As DbSet(Of BALANCE_SHEET)
    Public Overridable Property BALANCE_SHEET_TRANSACTION() As DbSet(Of BALANCE_SHEET_TRANSACTION)
    Public Overridable Property CONTENT_MANAGER() As DbSet(Of CONTENT_MANAGER)
    Public Overridable Property FILE_STORAGE() As DbSet(Of FILE_STORAGE)
    Public Overridable Property FINANCE_DECISIONS() As DbSet(Of FINANCE_DECISIONS)
    Public Overridable Property GAMEs() As DbSet(Of GAME)
    Public Overridable Property GAME_FIRM() As DbSet(Of GAME_FIRM)
    Public Overridable Property GAME_TYPE() As DbSet(Of GAME_TYPE)
    Public Overridable Property IMAGE_STRING() As DbSet(Of IMAGE_STRING)
    Public Overridable Property INCOME_STATEMENT() As DbSet(Of INCOME_STATEMENT)
    Public Overridable Property MARKET_INFO() As DbSet(Of MARKET_INFO)
    Public Overridable Property MARKETING_DECISIONS() As DbSet(Of MARKETING_DECISIONS)
    Public Overridable Property PERIODs() As DbSet(Of PERIOD)
    Public Overridable Property PRODUCTION_DECISIONS() As DbSet(Of PRODUCTION_DECISIONS)
    Public Overridable Property RESULTs() As DbSet(Of RESULT)
    Public Overridable Property REVENUE_AND_COST() As DbSet(Of REVENUE_AND_COST)
    Public Overridable Property RND_DECISIONS() As DbSet(Of RND_DECISIONS)
    Public Overridable Property USERs() As DbSet(Of USER)
    Public Overridable Property USER_ROLE() As DbSet(Of USER_ROLE)
    Public Overridable Property USER_USER_ROLE_GAME_FIRM_RELATIONSHIP() As DbSet(Of USER_USER_ROLE_GAME_FIRM_RELATIONSHIP)
    Public Overridable Property VIDEO_STORAGE() As DbSet(Of VIDEO_STORAGE)
    Public Overridable Property WEB_API_AUTHORIZATION() As DbSet(Of WEB_API_AUTHORIZATION)
    Public Overridable Property WEB_API_TRANSACTION() As DbSet(Of WEB_API_TRANSACTION)

    Public Overridable Function GetEntityClass(tableName As String) As Integer
        Dim tableNameParameter As ObjectParameter = If(tableName IsNot Nothing, New ObjectParameter("TableName", tableName), New ObjectParameter("TableName", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("GetEntityClass", tableNameParameter)
    End Function

End Class
