'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GAME
    Public Property ID As Integer
    Public Property GAME_NAME As String
    Public Property GAME_TYPE_LINK_ID As Nullable(Of Integer)
    Public Property IS_DELETED As Nullable(Of Boolean)
    Public Property IMAGE_MANAGER_LINK_ID As Nullable(Of Integer)
    Public Property STATUS As Nullable(Of Integer)
    Public Property GAME_PASSWORD As String
    Public Property DESCRIPTION As String

    Public Overridable Property CONTENT_MANAGER As CONTENT_MANAGER
    Public Overridable Property GAME_FIRM As ICollection(Of GAME_FIRM) = New HashSet(Of GAME_FIRM)
    Public Overridable Property GAME_TYPE As GAME_TYPE
    Public Overridable Property PERIODs As ICollection(Of PERIOD) = New HashSet(Of PERIOD)
    Public Overridable Property USER_USER_ROLE_GAME_FIRM_RELATIONSHIP As ICollection(Of USER_USER_ROLE_GAME_FIRM_RELATIONSHIP) = New HashSet(Of USER_USER_ROLE_GAME_FIRM_RELATIONSHIP)

End Class
