'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GAME_FIRM
    Public Property ID As Integer
    Public Property FIRM_NAME As String
    Public Property GAME_LINK_ID As Nullable(Of Integer)
    Public Property IS_DELETED As Nullable(Of Boolean)
    Public Property DESCRIPTION As String
    Public Property MAX_NUMBER_OF_PLAYER As Nullable(Of Integer)
    Public Property BALANCE_SHEET_LINK_ID As Nullable(Of Integer)
    Public Property PRODUCTION_PRICE As Nullable(Of Double)
    Public Property PRODUCTION_QUALITY As Nullable(Of Integer)
    Public Property MARKET_SHARE As Nullable(Of Double)
    Public Property MARKET_SHARE_QTY As Nullable(Of Integer)
    Public Property MARKET_INFO_LINK_ID As Nullable(Of Integer)
    Public Property ALPHA_VALUE As Nullable(Of Double)
    Public Property PRODUCTION_COST As Nullable(Of Double)

    Public Overridable Property BALANCE_SHEET As BALANCE_SHEET
    Public Overridable Property GAME As GAME
    Public Overridable Property MARKET_INFO As MARKET_INFO
    Public Overridable Property INCOME_STATEMENT As ICollection(Of INCOME_STATEMENT) = New HashSet(Of INCOME_STATEMENT)
    Public Overridable Property MARKETING_DECISIONS As ICollection(Of MARKETING_DECISIONS) = New HashSet(Of MARKETING_DECISIONS)
    Public Overridable Property PRODUCTION_DECISIONS As ICollection(Of PRODUCTION_DECISIONS) = New HashSet(Of PRODUCTION_DECISIONS)
    Public Overridable Property RESULTs As ICollection(Of RESULT) = New HashSet(Of RESULT)
    Public Overridable Property RESULTs1 As ICollection(Of RESULT) = New HashSet(Of RESULT)
    Public Overridable Property REVENUE_AND_COST As ICollection(Of REVENUE_AND_COST) = New HashSet(Of REVENUE_AND_COST)
    Public Overridable Property RND_DECISIONS As ICollection(Of RND_DECISIONS) = New HashSet(Of RND_DECISIONS)
    Public Overridable Property USER_USER_ROLE_GAME_FIRM_RELATIONSHIP As ICollection(Of USER_USER_ROLE_GAME_FIRM_RELATIONSHIP) = New HashSet(Of USER_USER_ROLE_GAME_FIRM_RELATIONSHIP)

End Class
