'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class INCOME_STATEMENT
    Public Property ID As Integer
    Public Property REVENUE_JSON As Nullable(Of Double)
    Public Property COST_JSON As Nullable(Of Double)
    Public Property PROFIT As Nullable(Of Double)
    Public Property FIRM_LINK_ID As Nullable(Of Integer)
    Public Property PERIOD_LINK_ID As Nullable(Of Integer)

    Public Overridable Property GAME_FIRM As GAME_FIRM
    Public Overridable Property PERIOD As PERIOD

End Class
