'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MARKETING_DECISIONS
    Public Property ID As Integer
    Public Property PRICE As Nullable(Of Decimal)
    Public Property IN_GAME_TIME_IN_DAY As Nullable(Of Decimal)
    Public Property FIRM_LINK_ID As Nullable(Of Integer)
    Public Property PERIOD_LINK_ID As Nullable(Of Integer)
    Public Property USER_LINK_ID As Nullable(Of Integer)
    Public Property IS_DELETED As Nullable(Of Boolean)

    Public Overridable Property GAME_FIRM As GAME_FIRM
    Public Overridable Property PERIOD As PERIOD
    Public Overridable Property USER As USER
    Public Overridable Property RESULTs As ICollection(Of RESULT) = New HashSet(Of RESULT)

End Class
