'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PERIOD
    Public Property ID As Integer
    Public Property PERIOD_NAME As String
    Public Property PERIOD_NUMBER As Nullable(Of Integer)
    Public Property STATUS As Nullable(Of Integer)
    Public Property START_TIME As Nullable(Of Date)
    Public Property END_TIME As Nullable(Of Date)
    Public Property IS_DELETED As Nullable(Of Boolean)
    Public Property EXPECTED_START As Nullable(Of Date)
    Public Property EXPECTED_END As Nullable(Of Date)
    Public Property SIMULATION_DURATION As Nullable(Of Decimal)
    Public Property GAME_LINK_ID As Nullable(Of Integer)

    Public Overridable Property GAME As GAME
    Public Overridable Property INCOME_STATEMENT As ICollection(Of INCOME_STATEMENT) = New HashSet(Of INCOME_STATEMENT)
    Public Overridable Property MARKETING_DECISIONS As ICollection(Of MARKETING_DECISIONS) = New HashSet(Of MARKETING_DECISIONS)
    Public Overridable Property PRODUCTION_DECISIONS As ICollection(Of PRODUCTION_DECISIONS) = New HashSet(Of PRODUCTION_DECISIONS)
    Public Overridable Property RESULTs As ICollection(Of RESULT) = New HashSet(Of RESULT)
    Public Overridable Property REVENUE_AND_COST As ICollection(Of REVENUE_AND_COST) = New HashSet(Of REVENUE_AND_COST)
    Public Overridable Property RND_DECISIONS As ICollection(Of RND_DECISIONS) = New HashSet(Of RND_DECISIONS)

End Class
