'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class USER_USER_ROLE_GAME_FIRM_RELATIONSHIP
    Public Property ID As Integer
    Public Property USER_LINK_ID As Nullable(Of Integer)
    Public Property USER_ROLE_LINK_ID As Nullable(Of Integer)
    Public Property GAME_LINK_ID As Nullable(Of Integer)
    Public Property FIRM_LINK_ID As Nullable(Of Integer)
    Public Property IS_DELETED As Nullable(Of Boolean)

    Public Overridable Property GAME As GAME
    Public Overridable Property GAME_FIRM As GAME_FIRM
    Public Overridable Property USER As USER
    Public Overridable Property USER_ROLE As USER_ROLE

End Class
