'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VIDEO_STORAGE
    Public Property ID As Integer
    Public Property NAME As String
    Public Property VIDEO_STRING As String
    Public Property IS_DELETED As Nullable(Of Boolean)

    Public Overridable Property CONTENT_MANAGER As ICollection(Of CONTENT_MANAGER) = New HashSet(Of CONTENT_MANAGER)

End Class
