'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class WEB_API_AUTHORIZATION
    Public Property ID As Integer
    Public Property LOGGED_IN_PERSONNEL_LINK_ID As Nullable(Of Integer)
    Public Property LOGGED_IN_DATE_TIME As Nullable(Of Date)
    Public Property UNIQUE_TOKEN As String
    Public Property EXPIRE_DATE_TIME As Nullable(Of Date)
    Public Property LAST_REQUESTED_DATE_TIME As Nullable(Of Date)
    Public Property REQUEST_COUNT As Nullable(Of Integer)
    Public Property IS_DELETED As Nullable(Of Boolean)

    Public Overridable Property USER As USER
    Public Overridable Property WEB_API_TRANSACTION As ICollection(Of WEB_API_TRANSACTION) = New HashSet(Of WEB_API_TRANSACTION)

End Class
