'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class WEB_API_TRANSACTION
    Public Property ID As Integer
    Public Property WEB_API_AUTHORIZATION_LINK_ID As Nullable(Of Integer)
    Public Property TRANSACTION_URL As String
    Public Property TRANSACTION_DATE_TIME As String
    Public Property TRANSACTION_TYPE As Nullable(Of Integer)
    Public Property TRANSACTION_HEADERS As String
    Public Property TRANSACTION_BODY As String
    Public Property USER_AGENT As String
    Public Property SERVER_VARIABLES As String

    Public Overridable Property WEB_API_AUTHORIZATION As WEB_API_AUTHORIZATION

End Class
